# Generated by Django 5.1.5 on 2025-02-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contact",
            table="portafolio_contact",
        ),
    ]
