name: Prueba con Django

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          python -m venv env/
          source env/bin/activate
          python -m pip install
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          virtual-environment: env/
    
    
