name: Prueba con Django

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkpout@v4
      - name: 'Hello work'
        run: echo "Hello work"
      - name: Dime la fecha
        run: date
    
    
